# Generated by Django 5.2.14 on 2026-05-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='MetaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuantidadeEsperada', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Tarefas Estipuladas:')),
            ],
            options={
                'verbose_name': 'Meta Diaria',
                'verbose_name_plural': 'Metas Diarias',
            },
        ),
        migrations.CreateModel(
            name='Prioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo da prioridade')),
            ],
            options={
                'verbose_name': 'Prioridade',
                'verbose_name_plural': 'Prioridades',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo do status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo do usuário')),
            ],
            options={
                'verbose_name': 'Tipo do Usuário',
                'verbose_name_plural': 'Tipos de Usuários',
            },
        ),
        migrations.CreateModel(
            name='RelatorioDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome do Relatório')),
                ('StatusConcluida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Monitoramento: Status Concluído')),
            ],
            options={
                'verbose_name': 'Relatorio de Desempenho',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo da Tarefa')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao da Tarefa')),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataConclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria', verbose_name='Categoria da Tarefa')),
                ('prioridade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prioridade', verbose_name='Prioridade da Tarefa')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.status', verbose_name='Status da Tarefa')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
        migrations.CreateModel(
            name='SubTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome da subTarefa')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descricao da subTarefa')),
                ('tarefaMae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarefa', verbose_name='Tarefa Mãe')),
            ],
            options={
                'verbose_name': 'Sub tarefa',
                'verbose_name_plural': 'Sub Tarefas ',
            },
        ),
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do Lembrete')),
                ('disparo', models.DateTimeField()),
                ('tarefaMae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarefa')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
            },
        ),
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='texto da anotação')),
                ('dataCriacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('tarefaAnotada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarefa', verbose_name='Tarefa Mãe')),
            ],
            options={
                'verbose_name': 'Anotacao',
                'verbose_name_plural': 'Anotacoes',
            },
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome do arquivo')),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('tarefaMae', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tarefa')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('email', models.EmailField(max_length=100, verbose_name='Email do usuário')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha do usuário')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipouser', verbose_name='Tipo do usuário')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Usuário dono da tarefa'),
        ),
    ]
