# Generated by Django 5.2.12 on 2026-03-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodisciplina',
            options={'verbose_name': 'Curso Disciplina', 'verbose_name_plural': 'Cursos Disciplinas'},
        ),
    ]
