# Generated by Django 5.2.12 on 2026-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cursodisciplina_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(default='1', max_length=100, verbose_name='Periodo'),
        ),
    ]
