# Generated by Django 5.2.12 on 2026-04-06 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cidade_options_alter_cidade_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplina',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina'),
        ),
    ]
