# Generated by Django 5.2.12 on 2026-04-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_curso_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma Aluno:'),
        ),
    ]
